export const LOAD_GADGETS = 'LOAD_GADGETS';
export const LOAD_GADGET_CATEGORIES = 'LOAD_GADGET_CATEGORIES';

export const CREATE_GADGET = 'CREATE_GADGET';
export const UPDATE_GADGET = 'UPDATE_GADGET';
export const DELETE_GADGET = 'DELETE_GADGET';