export default [
    'A.I. Code Cryptographer',
    'A.I. Kit',
    'Cipher-Scrambler',
    'Circuit Unit-Processor',
    'Coder-Encoder',
    'Coding Controlling Ruler PDA',
    'Coding Domination Manipulator',
    'Coding Network-Coder',
    'Coding Possesor',
    'Command Scrambler-Master',
    'Command-Computer',
    'Command-Mechanism',
    'Compu Crypto PDA',
    'Computer Controller-Tablet',
    'Computer PDA',
    'Computer Possesor-Ruler',
    'Computer-A.I.',
    'Computerized Circuit Processor',
    'Computerized System Manipulator',
    'Control-Code Computer',
    'Controlling Cipher-Ruler',
    'Controlling Computer-Director',
    'Crypto Cryptographic Processor',
    'Cryptographic Circuit-Unit',
    'Cybernetic Master',
    'Directing Cryptographic Network',
    'Directing Cryptography-Director',
    'Director-Mechanism',
    'Dominating A.I. Ruler Tablet',
    'Dominating Cryptographer-Ruler',
    'Dominating Cryptography-PDA',
    'Dominating Manipulating A.I.',
    'Dominating Manipulation-Pack',
    'Dominator-Encoder',
    'Dominator-Pack',
    'Dominator-Possesor',
    'Encoder-Kit',
    'Encoding Laptop',
    'Encoding Laptop Pack',
    'Integrated A.I.-Master',
    'Integrated Command Dominator',
    'Integrated Dominating Kit',
    'Integrated Scrambler',
    'Integrated Unit',
    'Manipulating Ruling Control Cryptographer',
    'Manipulation-Computer Possesor',
    'Manipulation-Possesor',
    'Manipulation-Scrambler',
    'Mastery Laptop',
    'Mastery Pack',
    'Mastery-Ruler Controller',
    'Module-A.I.',
    'Network-Module',
    'Networked Encoding Ruler Possesor',
    'Networked System',
    'Pack-Director',
    'Rule A.I.',
    'Rule Code Possesor',
    'Rule Cybernetic Ruler',
    'Ruler-Computer Possesor',
    'Ruler-Kit',
    'Ruler-Manipulation Dominator',
    'Ruler-Module',
    'Ruler-Possesor',
    'Ruler-Scrambler',
    'Ruling Cryptographer-Computer',
    'Ruling Laptop Cryptography Ruler',
    'Ruling Possesor',
    'System Computer',
    'System Pack',
    'System Processor',
    'Tablet-Coder',
    'Tablet-Controller'
];