export const LOAD_WIDGETS = 'LOAD_WIDGETS';
export const LOAD_WIDGET_CATEGORIES = 'LOAD_WIDGET_CATEGORIES';

export const CREATE_WIDGET = 'CREATE_WIDGET';
export const UPDATE_WIDGET = 'UPDATE_WIDGET';
export const DELETE_WIDGET = 'DELETE_WIDGET';